<?php

namespace App\Services\Import;

use App\Enums\DecorationCategory;
use App\Enums\VariantExistence;
use App\Models\Color;
use App\Models\Decoration;
use App\Models\Line;
use App\Models\Product;
use App\Models\Variant;
use App\Services\BaseService;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

/**
 * Builds the reference catalog: lines, colors, products and the variant cross
 * product.
 *
 * The detail tab is authoritative. The matrix tab contributes colors the detail
 * tab lacks, and nothing else. Variants are generated by crossing colors and
 * products within a single line, because a Harlequin teapot and a Fiesta teapot
 * are different objects; crossing globally would produce combinations that are
 * not merely unverified but incoherent.
 */
class CatalogImporter extends BaseService
{
    public function __construct(
        private SeedDataReader $reader,
    ) {}

    /** @var array<string, array{decoration: Decoration, color: string, color_produced_from: ?int}> */
    private array $decorations = [];

    public function import(ImportReport $report): void
    {
        $lines = $this->importLines();
        $this->importDecorations($report);
        $this->importDetailColors($lines, $report);
        $this->importMatrixColors($lines[SeedDataReader::LINE_FIESTA], $report);
        $this->importShapes($lines, $report);
        $this->importHexValues($report);
        $this->buildVariants($report);
        $this->buildDecoratedVariants($lines, $report);
    }

    /**
     * Applied decorations such as decals.
     *
     * A decorated piece is not a color of its own: the glaze underneath has a
     * name already, and the decoration has its own production run. Rows named
     * here are held back from the color axis so they do not pollute it.
     */
    private function importDecorations(ImportReport $report): void
    {
        $rows = $this->reader->decorationRows();

        if ($rows === null) {
            return;
        }

        foreach ($rows as $row) {
            $decoration = Decoration::firstOrCreate(
                ['name' => $row['decoration']],
                [
                    'category' => $row['category'] !== '' ? DecorationCategory::from($row['category']) : null,
                    'produced_from' => $row['produced_from'],
                    'produced_to' => $row['produced_to'],
                    'notes' => $row['notes'] !== '' ? $row['notes'] : null,
                ]
            );

            $this->decorations[mb_strtolower($row['source_name'])] = [
                'decoration' => $decoration,
                'color' => $row['color'],
                'color_produced_from' => $row['color_produced_from'],
            ];

            $report->add(
                'Decorations read as decoration, not color',
                "\"{$row['source_name']}\" in the export is the {$row['decoration']} decoration on "
                ."{$row['color']}, not a color of its own."
            );
        }

        $report->set('decorations', count($rows));
    }

    /**
     * Decorated variants are never part of the cross product. One is created
     * only where the collection export actually shows that product carrying that
     * decoration, so the catalog never invents decorated combinations.
     *
     * @param  array<string, Line>  $lines
     */
    private function buildDecoratedVariants(array $lines, ImportReport $report): void
    {
        if ($this->decorations === []) {
            return;
        }

        $created = 0;

        foreach ($this->reader->detailRows() as $row) {
            $entry = $this->decorations[mb_strtolower(SeedDataReader::parseColor($row['color'])['name'])] ?? null;
            $productParsed = SeedDataReader::parseProduct($row['type']);

            if ($entry === null || $productParsed === null) {
                continue;
            }

            $line = $lines[$row['line']];
            $color = $this->findColor($line->id, $entry['color'], $entry['color_produced_from']);
            $product = Product::where('line_id', $line->id)->whereRaw('lower(name) = ?', [$productParsed['key']])->first();

            if ($color === null || $product === null) {
                $report->add(
                    'Decorated pieces not placed',
                    "Row {$row['row']}: \"{$row['color']}\" / \"{$row['type']}\" could not resolve "
                    .($color === null ? "the {$entry['color']} glaze" : 'the product').'.'
                );

                continue;
            }

            Variant::firstOrCreate(
                ['product_id' => $product->id, 'color_id' => $color->id, 'decoration_id' => $entry['decoration']->id],
                ['existence' => VariantExistence::Confirmed]
            );

            $created++;
        }

        $report->set('decorated variants', $created);
    }

    /**
     * Swatch colors, if the owner has supplied them.
     *
     * A color's hex value is reference data, so none is generated here. The
     * file is optional: without it every swatch renders as a placeholder that
     * reads as missing rather than as a made up color.
     */
    private function importHexValues(ImportReport $report): void
    {
        $rows = $this->reader->hexRows();

        if ($rows === null) {
            $report->add(
                'Swatches',
                'No color-hex.csv found. Swatches will render as placeholders.'
            );

            return;
        }

        $fiestaId = Line::where('name', SeedDataReader::LINE_FIESTA)->value('id');
        $filled = 0;

        foreach ($rows as $row) {
            if (! preg_match('/^#[0-9a-fA-F]{6}$/', $row['hex'])) {
                $report->add(
                    'Swatches: unreadable hex values',
                    "Row {$row['row']}: \"{$row['name']}\" gives \"{$row['hex']}\", which is not a #rrggbb value. Skipped."
                );

                continue;
            }

            $name = SeedDataReader::parseHexName($row['name']);
            $color = $this->findColor($fiestaId, $name, $row['produced_from']);

            if ($color === null) {
                $color = $this->matchHexByNameAlone($fiestaId, $name, $row, $report);
            }

            if ($color === null) {
                $report->add(
                    'Swatches: colors not in the catalog',
                    "Row {$row['row']}: \"{$row['name']}\" ({$row['produced_from']}) has no catalog color. "
                    .'The catalog only contains colors evidenced by your collection export.'
                );

                continue;
            }

            $color->update(['hex' => strtolower($row['hex'])]);
            $filled++;

            $this->reportHexYearConflict($color, $row, $report);
        }

        $report->set('colors with a swatch', $filled);
        $report->set('colors still without a swatch', Color::whereNull('hex')->count());

        foreach (Color::with('line')->whereNull('hex')->get() as $color) {
            $report->add(
                'Swatches: catalog colors still without one',
                "{$color->line->name} \"{$color->name}\" (".($color->produced_label ?? 'no years').')'
            );
        }
    }

    /**
     * The swatch list and the collection export sometimes disagree on a start
     * year. Where the name is unique in the catalog the row is still matched,
     * and the discrepancy is reported rather than resolved.
     */
    private function matchHexByNameAlone(int $fiestaId, string $name, array $row, ImportReport $report): ?Color
    {
        $matches = Color::where('line_id', $fiestaId)->where('name', $name)->get();

        if ($matches->count() !== 1) {
            return null;
        }

        $report->add(
            'Swatches: start years disagree',
            "Row {$row['row']}: \"{$row['name']}\" starts {$row['produced_from']} in the swatch list but "
            .$matches->first()->produced_from.' in the catalog. Matched on name; years left as they are.'
        );

        return $matches->first();
    }

    /**
     * The swatch list carries end years too. They are recorded as conflicts and
     * never written: changing production years is a separate decision.
     */
    private function reportHexYearConflict(Color $color, array $row, ImportReport $report): void
    {
        if ($color->produced_to === $row['produced_to']) {
            return;
        }

        $report->add(
            'Swatches: end years disagree with the collection export',
            "\"{$color->name}\" ".($color->produced_label ?? 'no years').' in the catalog, but the swatch list says '
            .$row['produced_from'].'-'.($row['produced_to'] ?? '').'. Not applied.'
        );
    }

    /** @return array<string, Line> */
    private function importLines(): array
    {
        $lines = [];

        foreach ([SeedDataReader::LINE_FIESTA, SeedDataReader::LINE_RIVIERA, SeedDataReader::LINE_HARLEQUIN] as $name) {
            $lines[$name] = Line::firstOrCreate(['name' => $name], ['slug' => Str::slug($name)]);
        }

        return $lines;
    }

    /**
     * Colors from the detail tab.
     *
     * Riviera and Harlequin rows reuse Fiesta color strings with Fiesta's
     * production years embedded. Copying those years across lines would be
     * fabricating reference data, so non-Fiesta colors are created with null
     * years and no era until the owner supplies real ranges.
     *
     * @param  array<string, Line>  $lines
     */
    private function importDetailColors(array $lines, ImportReport $report): void
    {
        foreach ($this->reader->detailRows() as $row) {
            if (isset($this->decorations[mb_strtolower(SeedDataReader::parseColor($row['color'])['name'])])) {
                continue;
            }

            $parsed = SeedDataReader::parseColor($row['color']);
            $line = $lines[$row['line']];
            $isFiesta = $row['line'] === SeedDataReader::LINE_FIESTA;

            $from = $isFiesta ? $parsed['from'] : null;
            $to = $isFiesta ? $parsed['to'] : null;

            $existing = $this->findColor($line->id, $parsed['name'], $from);

            if ($existing === null) {
                Color::create([
                    'line_id' => $line->id,
                    'name' => $parsed['name'],
                    'produced_from' => $from,
                    'produced_to' => $to,
                ]);

                if (! $isFiesta && $parsed['from'] !== null) {
                    $report->add(
                        'Line colors created without production years',
                        "{$row['line']} \"{$parsed['name']}\" (row {$row['row']}): the sheet carries "
                        ."{$parsed['from']}-{$parsed['to']}, which is Fiesta's range. Stored as null; era unavailable until supplied."
                    );
                }

                continue;
            }

            if ($isFiesta && $existing->produced_to !== $to) {
                $report->add(
                    'Conflicting end years for the same color',
                    "Fiesta \"{$parsed['name']}\" starting {$from}: stored end year "
                    .var_export($existing->produced_to, true).', row '.$row['row'].' says '.var_export($to, true).'. Kept the stored value.'
                );
            }
        }
    }

    /**
     * Colors from the matrix tab, which has no line dimension and is therefore
     * treated as Fiesta.
     *
     * Matrix rows in the vintage block carry no year range at all. Where such a
     * name already exists, the row is attached to the earliest matching color
     * rather than creating a duplicate yearless row.
     */
    private function importMatrixColors(Line $fiesta, ImportReport $report): void
    {
        foreach ($this->reader->matrixRows() as $row) {
            $parsed = SeedDataReader::parseColor($row['color']);

            if ($parsed['from'] !== null) {
                if ($this->findColor($fiesta->id, $parsed['name'], $parsed['from']) === null) {
                    Color::create([
                        'line_id' => $fiesta->id,
                        'name' => $parsed['name'],
                        'produced_from' => $parsed['from'],
                        'produced_to' => $parsed['to'],
                    ]);

                    $report->add(
                        'Colors present only in the matrix tab',
                        "\"{$row['color']}\" (matrix row {$row['row']}) has no rows in the detail tab."
                    );

                    if ($parsed['from'] === $parsed['to']) {
                        $report->add(
                            'Single year colors, read as discontinued',
                            "\"{$row['color']}\" (matrix row {$row['row']}) gives one year and no trailing dash, so it "
                            ."reads as produced only in {$parsed['from']}. If it is still in production the sheet needs a trailing dash."
                        );
                    }
                }

                continue;
            }

            $matches = Color::where('line_id', $fiesta->id)
                ->where('name', $parsed['name'])
                ->orderByRaw('produced_from is null, produced_from')
                ->get();

            if ($matches->isEmpty()) {
                Color::create(['line_id' => $fiesta->id, 'name' => $parsed['name']]);

                $report->add(
                    'Matrix colors with no year range and no match',
                    "\"{$row['color']}\" (matrix row {$row['row']}) created with null years."
                );

                continue;
            }

            if ($matches->count() > 1) {
                $report->add(
                    'Matrix colors with no year range',
                    "\"{$row['color']}\" (matrix row {$row['row']}) matches {$matches->count()} colors: "
                    .$matches->map(fn (Color $c) => $c->produced_label ?? 'no years')->implode(', ')
                    .'. Attached to the earliest.'
                );
            }
        }
    }

    /**
     * Shapes come from the detail tab's Type column, scoped to the line on the
     * row. Only casing and whitespace are normalized. Semantic collapses such
     * as "nappy bowl" versus "Nappy 8.5\"" are reported for the owner to rule
     * on rather than applied here.
     *
     * @param  array<string, Line>  $lines
     */
    private function importShapes(array $lines, ImportReport $report): void
    {
        $seen = [];

        foreach ($this->reader->detailRows() as $row) {
            $parsed = SeedDataReader::parseProduct($row['type']);

            if ($parsed === null) {
                continue;
            }

            $line = $lines[$row['line']];
            $key = $line->id.'|'.$parsed['key'];

            if (isset($seen[$key])) {
                if ($seen[$key] !== $parsed['raw']) {
                    $report->add(
                        'Product spellings merged on casing',
                        "\"{$parsed['raw']}\" (row {$row['row']}) merged into \"{$parsed['display']}\" for {$row['line']}."
                    );
                }

                continue;
            }

            $seen[$key] = $parsed['raw'];
            Product::firstOrCreate(['line_id' => $line->id, 'name' => $parsed['display']]);
        }

        $this->reportUnmappedMatrixColumns($report);
        $this->reportShapeCollapseCandidates($report);
    }

    private function reportUnmappedMatrixColumns(ImportReport $report): void
    {
        foreach ($this->reader->matrixColumns() as $column) {
            if (! array_key_exists($column, SeedDataReader::MATRIX_PRODUCT_MAP)) {
                $report->add(
                    'Matrix columns with no unambiguous product',
                    "\"{$column}\" is a category rather than a single product and was not mapped. "
                    .'Holdings in this column are only imported for colors the detail tab already covers.'
                );
            }
        }
    }

    /**
     * Product names that look like they describe the same object. These are
     * reference decisions, so they are surfaced rather than applied.
     */
    private function reportShapeCollapseCandidates(ImportReport $report): void
    {
        $groups = [
            ['Canniser, Small', 'Cannister, Large'],
            ['Nappy 8.5"', 'Nappy Bowl'],
            ['Fruit Bowl', '7" Bowl', 'Oatmeal Bowl', 'Cream Soup'],
            ['Individual Salad', 'Unlisted Salad', '7" Plate'],
            ['Mini Disk Pitcher', 'Disk Pitcher', 'Juice Pitcher', 'Pitcher'],
            ['Batter Jug', 'Ring Handled Jug'],
            ['Salt and Pepper', 'Range Salt and Pepper'],
        ];

        foreach ($groups as $group) {
            $present = Product::whereIn('name', $group)->distinct()->pluck('name')->all();

            if (count($present) > 1) {
                $report->add(
                    'Product names that may describe one object',
                    implode(' / ', $present).' - kept separate pending your ruling.'
                );
            }
        }
    }

    /**
     * Cross colors and products within each line. Every generated row starts
     * unconfirmed; the holdings import promotes the ones with evidence.
     */
    private function buildVariants(ImportReport $report): void
    {
        $now = now();
        $total = 0;

        foreach (Line::with(['colors:id,line_id', 'products:id,line_id'])->get() as $line) {
            $rows = [];

            foreach ($line->products as $product) {
                foreach ($line->colors as $color) {
                    $rows[] = [
                        'product_id' => $product->id,
                        'color_id' => $color->id,
                        'existence' => VariantExistence::Unconfirmed->value,
                        'created_at' => $now,
                        'updated_at' => $now,
                    ];
                }
            }

            foreach (array_chunk($rows, 500) as $chunk) {
                Variant::insertOrIgnore($chunk);
            }

            $count = count($rows);
            $total += $count;

            $report->set(
                "variants generated: {$line->name} ({$line->colors->count()} colors x {$line->products->count()} products)",
                $count
            );
        }

        $report->set('variants generated: total', $total);
        $report->set('colors', DB::table('colors')->count());
        $report->set('products', DB::table('products')->count());
    }

    private function findColor(int $lineId, string $name, ?int $from): ?Color
    {
        $query = Color::where('line_id', $lineId)->where('name', $name);

        $from === null
            ? $query->whereNull('produced_from')
            : $query->where('produced_from', $from);

        return $query->first();
    }
}
